---
title: "07_changes"
format:
  html:
    code-fold: true
---


Here we look a changes over time for individual species as well as for the aggregate.  We bin abundance into a hexagonal mesh covering the area, compute long term means and the examine trends over time relative to each long-term mean. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("setup.R")
```


```{r load_data}
x = read_ecomon_spp(form = 'sf') |> ecomon_to_long()
h = read_hexgrid()
coast = read_coast()
plot(sf::st_geometry(x), pch = ".", axes = TRUE, reset = FALSE, main = "All records")
plot(sf::st_geometry(h), border = "gray", add = TRUE)
plot(coast, col = "orange", add = TRUE)
```


# Summaries across all time

Here we create long term total and mean per hexagon

```{r total_abundance}
totabund = tally_abundance(x, h, fun = sum, na.rm = TRUE, shape = "long") |>
  #dplyr::mutate(value = log(value+0.01)) |> 
  wider_abundance()
nbreaks = 10
plot(totabund,
     nbreaks = nbreaks,
     pal = RColorBrewer::brewer.pal(nbreaks-1, "Greens"))
```


# Mean abudance

```{r plot_each}
mabund = tally_abundance(x, h, fun = mean, na.rm = TRUE, 
                         shape = "long") |>
  wider_abundance()
nbreaks = 10
plot(mabund,
     nbreaks = nbreaks,
     pal = RColorBrewer::brewer.pal(nbreaks-1, "Blues"))
```
  
# Decadal abundance

```{r}
decades = seq(as.Date("1970-01-01"), as.Date("2020-01-01"), by = "10 years")
y = dplyr::mutate(x,
                  decade = decades[findInterval(.data$date, decades)]) |>
  group_by(name, decade) |>
  group_map(
    function(tbl, key){
      tally_by_poly(tbl, h, fun = mean, na.rm = TRUE, shape = "long") |>
        dplyr::mutate(name = key$name, decade = key$decade, .before = 1) |>
        write_abundance(sprintf("%s_%s_mean",
                                format(key$decade, "%Y"),
                                key$name))
    }
  ) |>
  dplyr::bind_rows()
```

```{r}
ta = tally_abundance(x, h, fun = mean, na.rm = TRUE, shape = "long") |>
  dplyr::filter(name == "total_10m2")
```


```{r}
dy = y |>
  dplyr::filter(name == "total_10m2") |>
  dplyr::group_by(decade) |>
  dplyr::group_map(
    function(tbl, key){
      d = tbl$value - ta$value
      dplyr::mutate(tbl, 
                    dvalue = d, 
                    decade = key$decade,
                    .after = dplyr::all_of("value"))  
    } ) |>
  dplyr::bind_rows()
```


```{r}

ggplot(dy) +
  geom_sf(color = "white", aes(fill = dvalue)) +
  geom_sf(data = coast) + 
  scale_fill_distiller(palette = "Spectral", na.value = NA) +
  facet_wrap(~decade)
```

