project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - index.qmd
    - 01_presences.qmd
    - 02_salps.qmd
    - 03_coel.qmd
    - 04_siph.qmd
    - 05_centop.qm
    - "!manuscript/"
    - "!*.Rmd"
execute: 
  cache: true
website:
  title: "Jellyscape"
  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Copyright 2025, Bigelow Laboratory for Ocean Science" 
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: 01_presences.qmd
        text: Presence of species
      - href: 02_salps.qmd
        text: Salps
      - href: 03_coel.qmd
        text: Coelenterates
      - href: 04_siph.qmd
        text: Siphonophores
      - href: 05_centop.qmd
        text: Ctenophores
      - href: about.qmd
        text: About
tools:
   - icon: github
     menu:
       - text: Tandy Center
         url:  https://www.bigelow.org/services/ocean-forecasting/
       - text: Source Code
         url:  https://github.com/BigelowLab/jellyscape
       - text: Report a bug or ask a question
         url:  https://github.com/BigelowLab/jellyscape/issues
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true
    
editor: source
