---
title: "Testing the Jelly Ocean Hypothesis in the Gulf of Maine"
author: "Nicholas R. Record, Benjamin Tupper"
date: 
output:
  pdf_document: default
  html_document: default
bibliography: bibliography.bib
csl: biomed-central.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

There has often been a “crustaceocentric” bias within zooplankton ecology in the ocean [@haddock2004golden]. The study of gelatinous species, collectively termed gelata, has been underemphasized as compared to crustaceans. In the early 2000s, gelata had a moment in the spotlight, following conspicuous blooms that damaged fisheries [@kideys2005impacts], aquaculture (ref), energy production (Seshadri et al. 2000), and recreation (ref). In addition to motivating new research on gelata, these events raised the question of whether there is a larger pattern of change emerging.

The Jelly Ocean Hypothesis posits that gelatinous zooplankton populations are increasing worldwide as a result of changing ocean conditions, primarily due to anthropogenic activities. A series of recent studies have argued that, due a multiplicity of causes, abundance of gelatinous species is growing. Proposed causes are primarily human-driven, including warming (ref), eutrophication, translocation [@kideys2005impacts], overfishing, bottom trawling (Qui 2014), pollution, aquaculture, and acidification [@richardson2008jellyfish]. There is also evidence that shifts toward dominance of gelata are difficult to reverse because of dynamics like histeresis [@richardson2009jellyfish]. 

Testing the Jelly Ocean Hypothesis requires long time series (>20 years) of gelata abundances in order to compare to historical levels. The shortage of such datasets has left the Jelly Ocean Hypothesis largely unsupported [@condon2012questioning]. In lieu of time series, studies have used qualitative data such as news reports to argue that gelata are increasing globally [@brotz2012increasing]. However, it is difficult to distinguish these perceived increases from multi-annual or multi-decadal fluctuations. A recent meta-analysis of time series showed that most perceived increases reflect a ~20 year cyclicity, with a worldwide upswing in the 1990s, coinciding with the increase in concern over gelata [@condon2013recurrent], although some notable long-term increases in gelata were not included in the analysis [@atkinson2004long]. The Jelly Ocean Hypothesis remains very much in debate [@sanz2016flawed].

In some ways, the Jelly Ocean Hypothesis is loosely posed. Gelata are taxonomically very diverse, encompassing multiple phyla. This diversity confounds attempts to quantify increasing trends. The list of species classified under the gelatinous umbrella varies, and includes taxa with drastic and important differences in their life histories, trophic positions, and ecological roles. For example, pelagic ctenophores are primarily copepod predators, where as pelagic tunicates graze some of the smallest microbes. Cnidarians and ctenophores are the two most common taxa to group together in analysis, and yet they are phylogenetically very distant (Moroz et al. 2014). Perhaps the only characteristic common to the many gelatinous phyla is a body with a high water content, alternatively expressed as a low carbon:volume ratio. There is no a priori reason to expect that phyla with such striking differences and perhaps only a superficial similarity should be grouped together with respect to their temporal trends. Some have suggested that the Jelly Ocean Hypothesis is ill-posed—i.e. which species are increasing, where, and for what reason (Gibbons & Richardson 2013)?

Despite their major differences, there is some evidence that a diverse collection of gelata can vary together (Condon et al. 2013). This suggests that certain conditions can occur that favor the gelatinous body form in general, over other strategies that utilize a high carbon:volume ratio (e.g. crustaceans). This reframes the Jelly Ocean Hypothesis in trait-based terms: conditions in the ocean ecosystem can shift to benefit the gelatinous body form. This would be inclusive of gelata in general, despite differences in phylogeny, trophic position, or other life history traits. 

We revisited the Jelly Ocean Hypothesis using a 50-year spatial survey on the northwest North Atlantic Shelf. We addressed two main questions: 1) what are the temporal changes in gelata presence; and 2) what are the underlying conditions associated with changes. We examined three taxonomic groups well-represented in the dataset--siphonophores, salps, and coelenterates--to explore the idea that certain conditions can favor the gelatinous body plan in general, rather a particulars.

## Methods

### Data

The Northeast Fisheries Science Center Ecosystem Monitoring (ECOMON) program collects seasonal zooplankton measurements as part of its mission to monitor and assess the Northeast Continental Shelf ecosystem. Sampling includes oblique tows using a 61 cm bongo net fitted with a 333 µm mesh at stratified locations across the shelf (Figure 1). Tows are a minimum of five minutes in duration and sample from the surface to within 5 m of the seabed or to a maximum depth of 200 m. A mechanical flowmeter fitted in the mouth of each net is used to quantify volume sampled. Gelatinous zooplankton are identified into broad taxonomic groups, including siphonophores, ctenophores, salps, and coelenterates (i.e. scyphozoans). The broad grouping, while missing ... has allowed for internal consistency over the duration of the survey. The analysis conducted here uses presence or absence of each taxonomic group.

### Time series analysis

### Spatial modeling

## Results

## Discussion

## References






